services:
  pr-mng-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pr-manage-service
    networks:
      - pr_mng_net
    ports:
      - "8080:8080"
    environment:
      DSN: postgres://postgres:password@pr_mng_db:5432/pr_mng_db?sslmode=disable
      ADMIN_TOKEN: admin
      MODE: debug
    depends_on:
      - pr_mng_db

  pr_mng_db:
    image: postgres:14-alpine
    container_name: pr_mng_db
    hostname: pr_mng_db
    ports:
      - "5432:5432"
    networks:
      - pr_mng_net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pr_mng_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

networks:
  pr_mng_net:
    driver: bridge

volumes:
  db_data:
